steps:
  # Build with BuildKit enabled explicitly via environment and using newer builder
  # Enable BuildKit
  - name: 'gcr.io/cloud-builders/docker'
    args: ['version']
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --name mybuilder --use && \
        docker buildx build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --build-arg COMMIT_SHA=$SHORT_SHA \
          --cache-from europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt:latest \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt:$SHORT_SHA \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt:latest \
          --load \
          .
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gsopt'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Make it public
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '60s'
      - '--cpu-throttling'
      - '--execution-environment'
      - 'gen2'
      - '--set-env-vars'
      - 'COMMIT_SHA=$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
