steps:
  # Debug step to verify substitution variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "COMMIT_SHA: $COMMIT_SHA"
        echo "SHORT_SHA: $SHORT_SHA"
        echo "PROJECT_ID: $PROJECT_ID"

  - name: 'gcr.io/cloud-builders/git'
    args: ['rev-parse', '--short', 'HEAD']
    id: 'get-commit-sha'
    env:
      - 'SHORT_SHA_FILE=/workspace/short_sha.txt'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'git rev-parse --short HEAD > /workspace/short_sha.txt'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'COMMIT_SHA=$(cat /workspace/short_sha.txt)'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gsopt:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gsopt:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gsopt'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gsopt:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/gsopt:latest'

options:
  logging: CLOUD_LOGGING_ONLY
