apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gsopt
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: europe-west1-docker.pkg.dev/gsopt-478412/cloud-run-source-deploy/gsopt:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        env:
        - name: COMMIT_SHA
          value: "REPLACE_AT_BUILD_TIME"
