steps:
  # Get the short commit SHA
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'git rev-parse --short HEAD | tee /workspace/commit_sha.txt'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$$(cat /workspace/commit_sha.txt)
        echo "Building with commit SHA: $$COMMIT_SHA"
        docker build \
          --build-arg COMMIT_SHA=$$COMMIT_SHA \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:$$COMMIT_SHA \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:latest \
          .

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tagged'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$$(cat /workspace/commit_sha.txt)
        docker push europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:$$COMMIT_SHA

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$$(cat /workspace/commit_sha.txt)
        gcloud run deploy gsopt \
          --image europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:$$COMMIT_SHA \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gsopt/gsopt:latest'

options:
  logging: CLOUD_LOGGING_ONLY
